### ISSUE TITLE
MacOS ck-qiskit "failed building wheel for pillow"

### ISSUE THREAD

**Issue by ballalan** [ctuning/ck-qiskit#4]
On Macos 10.10.5 (Yosemite)

After apparently successful install process,
Running this command : $ ck benchmark program:qiskit-demo --repetitions=1 --env.CK_IBM_BACKEND=ibmq_qasm_simulator --cmd_key=quantum_coin_flip --record_uoa=quantum_coin_flip --record --record_repo=remote-ck --record_experiment_repo=ck-quantum-hackathons

Get this outcome : Command "/usr/local/opt/python/bin/python3.7 -u -c "import setuptools, tokenize;__file__='/private/var/folders/jy/9s0s7k6j7_90wpbx17v2csnc0000gp/T/pip-install-8n9tokut/pillow/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /private/var/folders/jy/9s0s7k6j7_90wpbx17v2csnc0000gp/T/pip-record-xfabpki3/install-record.txt --single-version-externally-managed --prefix /Users/ballalan/CK-TOOLS/lib-qiskit-0.5.4-gcc-7.3.0-macos-64/python_deps_site --compile" failed with error code 1 in /private/var/folders/jy/9s0s7k6j7_90wpbx17v2csnc0000gp/T/pip-install-8n9tokut/pillow/
Error: installation failed!
CK error: [db25414b48b4ffb3] package installation failed!

Any suggestions ?

Thanks,

**Comment by ens-lg4** [comment]
Dear @ballalan, thanks for reporting this.

It is very surprising that the attempt to build the pillow's wheel is made at such a late stage.

Have you successfully run `ck run program:qiskit-demo --cmd_key=quantum_coin_flip` before running the benchmark command above?

**Comment by ballalan** [comment]
Oops! I had neglected to run this command: "ck install package:lib-python-qiskit".
After doing that, both runs of qiskit-demo appear to work.
Thanks,
