### ISSUE TITLE
Demo fails

### ISSUE THREAD

**Issue by chrisjonez** [ctuning/ck-qiskit#6]
I've tried running the following demo for this weekend's meetup, but it fails:

```
$ ck benchmark program:qiskit-demo --repetitions=1 --env.CK_IBM_BACKEND=ibmq_qasm_simulator --cmd_key=quantum_coin_flip --record_uoa=quantum_coin_flip --record --record_repo=remote-ck --record_experiment_repo=ck-quantum-hackathons
      
...log omitted...

    * tmp-stderr.tmp

      Traceback (most recent call last):
        File "../quantum_coin_flip.py", line 27, in <module>
          from qiskit import QuantumProgram, QISKitError, available_backends, register
      ImportError: cannot import name 'QuantumProgram'
      

  (reading fine grain timers from tmp-ck-timer.json ...)


Program execution likely failed (can't find fine grain timers)!

***************************************************************************************
Attempting to set CPU frequency to ondemand to "calm" system (if supported) ...


CMD to set CPU frequency:
  ck-set-cpu-ondemand
sh: 1: ck-set-cpu-ondemand: not found

  Warning: setting frequency possibly failed - return code 32512
***************************************************************************************
Attempting to set GPU frequency to ondemand to "calm" system (if supported) ...


CMD to set GPU frequency:
  ck-set-gpu-ondemand
sh: 1: ck-set-gpu-ondemand: not found

  Warning: setting frequency possibly failed - return code 32512
***************************************************************************************
Pipeline failed (execution failed - problem opening json file=tmp-ck-timer.json ([Errno 2] No such file or directory: 'tmp-ck-timer.json'))!
***************************************************************************************
Done!
***************************************************************************************
Some statistics:

* Failed: yes
* Reason: execution failed - problem opening json file=tmp-ck-timer.json ([Errno 2] No such file or directory: 'tmp-ck-timer.json')

* Binary size: 0
* Object size: 0

* Kernel repeat: 0

* Normalized time in sec. (min .. max): 0 .. 0

* Total time in us (min .. max): 0 .. 0

```
I get a similar error when I run the README demo:

```
$ ck run program:qiskit-demo --cmd_key=quantum_coin_flip

* qiskit-demo (3cf079d410d8f5aa)

... log omitted...

    * tmp-stderr.tmp

      Traceback (most recent call last):
        File "../quantum_coin_flip.py", line 27, in <module>
          from qiskit import QuantumProgram, QISKitError, available_backends, register
      ImportError: cannot import name 'QuantumProgram'
      

  (reading fine grain timers from tmp-ck-timer.json ...)


Program execution likely failed (can't find fine grain timers)!

```

**Comment by ens-lg4** [comment]
Dear @chrisjonez ,

Very recently QISKit have rolled out version 0.6 that is not yet compatible with CK code. You tried it late enough to get caught :)

Please run `ck pull all` to pick up the latest changes, `ck clean env -f` and start again.
Please let me know whether it helped or not. I'll keep the issue open.

**Comment by chrisjonez** [comment]
Cheers! Good and bad I'm afraid.

*The following command (from the README) seems to work now:*

$ ck run program:qiskit-demo --cmd_key=quantum_coin_flip
..omittied...
 (reading fine grain timers from tmp-ck-timer.json ...)

{
  "backends": [
    "local_qasm_simulator",
    "local_statevector_simulator",
    "local_unitary_simulator"
  ],
  "email": "N/A",
  "result": {
    "counts": {
      "00": 5,
      "11": 5
    },
    "snapshots": {}
  }
}


Execution time: 0.000 sec.

*But the other command:*

$ ck benchmark program:qiskit-demo --repetitions=1
--env.CK_IBM_BACKEND=ibmq_qasm_simulator --cmd_key=quantum_coin_flip
--record_uoa=quantum_coin_flip --record --record_repo=remote-ck
--record_experiment_repo=ck-quantum-hackathons

...omitted...

      ERROR
      Error in the circuit! 'QISKit timed out'


    * tmp-stderr.tmp

      Traceback (most recent call last):
        File "../quantum_coin_flip.py", line 110, in <module>
          'result':   result.get_data("bell"),
        File
"/home/cjones/CK-TOOLS/lib-python-qiskit-0.5.7-compiler.python-3.5.2-linux-64/build/qiskit/_result.py",
line 196, in get_data
          raise QISKitError(str(exception))
      qiskit._qiskiterror.QISKitError: 'QISKit timed out'


  (reading fine grain timers from tmp-ck-timer.json ...)


Program execution likely failed (can't find fine grain timers)!

***************************************************************************************
Attempting to set CPU frequency to ondemand to "calm" system (if supported)
...


CMD to set CPU frequency:
  ck-set-cpu-ondemand
sh: 1: ck-set-cpu-ondemand: not found

  Warning: setting frequency possibly failed - return code 32512
***************************************************************************************
Attempting to set GPU frequency to ondemand to "calm" system (if supported)
...


CMD to set GPU frequency:
  ck-set-gpu-ondemand
sh: 1: ck-set-gpu-ondemand: not found

  Warning: setting frequency possibly failed - return code 32512
***************************************************************************************
Pipeline failed (execution failed - problem opening json
file=tmp-ck-timer.json ([Errno 2] No such file or directory:
'tmp-ck-timer.json'))!
***************************************************************************************
Done!
***************************************************************************************
Some statistics:

* Failed: yes
* Reason: execution failed - problem opening json file=tmp-ck-timer.json
([Errno 2] No such file or directory: 'tmp-ck-timer.json')

* Binary size: 0
* Object size: 0

* Kernel repeat: 0

* Normalized time in sec. (min .. max): 0 .. 0

* Total time in us (min .. max): 0 .. 0

Any ideas?

**Comment by ens-lg4** [comment]
Thanks for trying!

If your API_Token was correct, it could just be the timeout for communication with the IBM QX machine. At the moment it is set to 60 seconds by default. Let's crank it up to 5 minutes just to be sure.

Could you please try running that long `ck benchmark` command again, having added
`--env.CK_IBM_TIMEOUT=300` to the end of it ?

**Comment by chrisjonez** [comment]
Yay, seems to have worked this time:

```
$ ck benchmark program:qiskit-demo --repetitions=1 --env.CK_IBM_BACKEND=ibmq_qasm_simulator --cmd_key=quantum_coin_flip --record_uoa=quantum_coin_flip --record --record_repo=remote-ck --record_experiment_repo=ck-quantum-hackathons --env.CK_IBM_TIMEOUT=300

...omitted...

***************************************************************************************
Pipeline executed successfully!
***************************************************************************************
Recording experiment ...


Recorded successfully in 0.89 secs.
***************************************************************************************
Done!
***************************************************************************************
Some statistics:

* Failed: no

* Binary size: 0
* Object size: 0

* Kernel repeat: 1

* Normalized time in sec. (min .. max): 0 .. 0

* Total time in us (min .. max): 0 .. 0


```

Thanks! Closing.
